### ISSUE TITLE
[CSS] Change color of video titles

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#10]
style.css:157

``` css
.more-vids-title {
    font-weight: 700;
    color: #546168;
}
```
