### ISSUE TITLE
[CSS] Change H3 styles on the homepage

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#11]
befunny.css:207

``` css
.more-posts h3 {
    margin-top: 0.8em;
    margin-bottom: 0.8em;
    line-height: 1em;
    font-weight: bold;
    font-size: 1.5em;
    color: #262b34;
}
```
