### ISSUE TITLE
[CSS] Serials: Change size and color of H3 tags

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#12]
befunny.css:310

``` css
h3.serial-name {
    margin: 0;
    font-weight: 700;
    font-size: 1.5em;
    color: #262b34;
}
```
