### ISSUE TITLE
[CSS & HTML] Styling of "View More Episodes" link in Web Series page

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#16]
Can we change the styling of the view more episodes link to look like this:

<img width="1106" alt="screen shot 2015-08-05 at 10 48 13 pm" src="https://cloud.githubusercontent.com/assets/10968955/9104684/5bdbf046-3bc4-11e5-94e4-55695c8cb01f.png">

Basically it adds `&rarr;` after the word "Episodes" as well as this CSS:

``` css
some class {
    font-family: 'Roboto Slab';
    font-weight: 700;
    font-size: 1em;
    color: #3bccff;
    border-bottom: 2px solid;
    padding-bottom: 6px;
    margin-top: 20px;
}

some class:hover {
    color: #91ffe8;
    border-color: #91ffe8;
}
```
