### ISSUE TITLE
[CSS] Change font weight on body

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#3]
Please change the body font weight to 400
Also remove the Source Sans Pro line to avoid conflicts later
Line 1254

``` css
media="all"
body {
    /* font-family: 'Source Sans Pro', sans-serif; */
    font-family: Roboto;
    font-size: 100%;
    font-weight: 400;
    line-height: 1.25;
    color: #333;
    -webkit-font-smoothing: antialiased;
}
```
