### ISSUE TITLE
[CSS] Change jumbotron <p> color

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#4]
Change the color of the jumbotron body text, not the headers
befunny.css:60

``` css
media="all"
.jb-caps p {
    color: #d6d6d6;
}
```
