### ISSUE TITLE
[CSS] Change icons and add right padding to give some more space

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#5]
For the time icon, in Fontello > Iconic collection, there's the 'clock' icon
For the play icon, in Fontello > Iconic collection, there's the 'play' icon
For the comments icon, in Fontello > Web Symbol collection, there's 'comment-alt'

Add padding-right of 5px to give space as well as color

``` css
media="all"
.icon-clock:before {
    content: '\e81e';
    padding-right: 5px;
    color: #3bccff;
}
```

``` css
media="all"
.icon-play-circled:before {
    content: '\e812';
    padding-right: 5px;
    color: #3bccff;
}
```
