### ISSUE TITLE
[CSS] Decrease padding of post container

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#7]
befunny.css:199

``` css
media="all"
.hp-posts-container {
    background: #fff;
    padding: 40px 0;
}
```
