### ISSUE TITLE
[CSS] Change color of hover state on main nav

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#8]
style.css:1899

``` css
.nav li a:hover, .nav li a:focus {
    color: #91ffe8;
}
```
