### ISSUE TITLE
[CSS] Change hover state color on text links

### ISSUE THREAD

**Issue by pyhkim** [befunnystudios/befunny-wp#9]
style.css:1251

``` css
media="all"
a:hover, a:focus, a:visited:hover, a:visited:focus {
    color: #67bbd4;
}
```
